name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install -r employee-api/requirements.txt
          pip install pytest httpx

      - name: Run calculator unit tests
        run: |
          python -m pytest "phase-4/Automated Testing/test_calculator.py"

      - name: Run employee API integration tests
        run: |
          cd employee-api
          python -m pytest test_api.py
